"""RAPTOR Mechanism Atlas -- condition-agnostic mechanism profile core.

Public API re-export surface. See ``src/raptor/atlas/README.md`` for the
module charter and boundaries. This package must never import from
``raptor.packet``, ``raptor.scorer``, ``raptor.eval``, or any Discovery
SDK (enforced by :func:`raptor.atlas.guards.assert_atlas_import_boundary`).
"""

from raptor.atlas.model import (
    AnchorSpec,
    AtlasCandidateImport,
    AtlasCatalogError,
    AtlasCatalogHashError,
    AtlasCatalogPathError,
    AtlasCatalogSchemaError,
    AtlasCitationResolutionError,
    AtlasContentDriftError,
    AtlasError,
    AtlasExportError,
    AtlasIdentity,
    AtlasIdentityError,
    AtlasIdentityMapAmbiguityError,
    AtlasIdentityMapBindingError,
    AtlasIdentityMapError,
    AtlasIdentityMapHashError,
    AtlasIdentityMapPathError,
    AtlasIdentityMapResponseError,
    AtlasIdentityMapSchemaError,
    AtlasLeakageError,
    AtlasLockDeltaError,
    AtlasPackError,
    AtlasPanelError,
    AtlasPanelInputError,
    AtlasPanelPackDriftError,
    AtlasPanelRegistrationError,
    AtlasProvenanceError,
    AtlasSchemaError,
    AtlasSourceVerificationError,
    AtlasSpanMismatchError,
    AtlasUniverseContractError,
    AtlasUniverseLockError,
    CandidateClass,
    CatalogSource,
    CitationIdentifier,
    CitationResolver,
    ContentVerification,
    ContextRecord,
    DisMechRecord,
    DiseasePack,
    EntryRef,
    EvidenceAssessment,
    MechanismEdge,
    MechanismProfile,
    ObservedClaim,
    PackBinding,
    Provenance,
    PromotionContext,
    RawIdentityMapper,
    RawIdentityReplay,
    ResolvedCitation,
    RunMetadata,
    SelectionInputs,
    SelectionRun,
    SourceRegisterEntry,
    Span,
    VerifiedSpan,
)
from raptor.atlas.identity import admit_identity, reconcile_transcript
from raptor.atlas.identity_map import (
    identity_map_content_hash,
    identity_map_lock_content_hash,
    load_identity_map,
)
from raptor.atlas.pack import load_disease_pack, pack_content_hash, validate_disease_pack
from raptor.atlas.panel import select_panel
from raptor.atlas.hashing import evidence_core_hash, profile_envelope_hash
from raptor.atlas.registry import validate_claim_grounding, verify_source
from raptor.atlas.profile import build_mechanism_profile
from raptor.atlas.promote import promote_candidate, validate_candidate_import
from raptor.atlas.export import export_dismech
from raptor.atlas.citation import (
    CitationCatalog,
    LocalCitationResolver,
    catalog_content_hash,
    load_catalog,
    normalize_identifier,
)
from raptor.atlas.guards import (
    assert_atlas_import_boundary,
    assert_no_consumer_import,
    assert_no_network_imports,
    scan_for_classification_leakage,
)

__all__ = [
    "AnchorSpec",
    "AtlasCandidateImport",
    "AtlasCatalogError",
    "AtlasCatalogHashError",
    "AtlasCatalogPathError",
    "AtlasCatalogSchemaError",
    "AtlasCitationResolutionError",
    "AtlasContentDriftError",
    "AtlasError",
    "AtlasExportError",
    "AtlasIdentity",
    "AtlasIdentityError",
    "AtlasIdentityMapAmbiguityError",
    "AtlasIdentityMapBindingError",
    "AtlasIdentityMapError",
    "AtlasIdentityMapHashError",
    "AtlasIdentityMapPathError",
    "AtlasIdentityMapResponseError",
    "AtlasIdentityMapSchemaError",
    "AtlasLeakageError",
    "AtlasLockDeltaError",
    "AtlasPackError",
    "AtlasPanelError",
    "AtlasPanelInputError",
    "AtlasPanelPackDriftError",
    "AtlasPanelRegistrationError",
    "AtlasProvenanceError",
    "AtlasSchemaError",
    "AtlasSourceVerificationError",
    "AtlasSpanMismatchError",
    "AtlasUniverseContractError",
    "AtlasUniverseLockError",
    "CandidateClass",
    "CatalogSource",
    "CitationCatalog",
    "CitationIdentifier",
    "CitationResolver",
    "ContentVerification",
    "ContextRecord",
    "DisMechRecord",
    "DiseasePack",
    "EntryRef",
    "EvidenceAssessment",
    "LocalCitationResolver",
    "MechanismEdge",
    "MechanismProfile",
    "ObservedClaim",
    "PackBinding",
    "Provenance",
    "PromotionContext",
    "RawIdentityMapper",
    "RawIdentityReplay",
    "ResolvedCitation",
    "RunMetadata",
    "SelectionInputs",
    "SelectionRun",
    "SourceRegisterEntry",
    "Span",
    "VerifiedSpan",
    "admit_identity",
    "reconcile_transcript",
    "identity_map_content_hash",
    "identity_map_lock_content_hash",
    "load_identity_map",
    "load_disease_pack",
    "pack_content_hash",
    "validate_disease_pack",
    "select_panel",
    "evidence_core_hash",
    "profile_envelope_hash",
    "validate_claim_grounding",
    "verify_source",
    "build_mechanism_profile",
    "promote_candidate",
    "validate_candidate_import",
    "export_dismech",
    "catalog_content_hash",
    "load_catalog",
    "normalize_identifier",
    "assert_atlas_import_boundary",
    "assert_no_consumer_import",
    "assert_no_network_imports",
    "scan_for_classification_leakage",
]
